import React from 'react';

export const styles = {
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '80px',
    backgroundColor: '#1a252f',
    color: '#ecf0f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: '2rem',
    paddingRight: '2rem',
    boxShadow: '0 2px 5px rgba(0, 0, 0, 0.1)',
    zIndex: 100,
  } as React.CSSProperties,
  companyName: {
    margin: 0,
    fontSize: '1.75rem',
    fontWeight: '700',
    letterSpacing: '0.5px',
  } as React.CSSProperties,
  companyNameMobile: {
    fontSize: '1.25rem',
    letterSpacing: '0.3px',
  } as React.CSSProperties,
  userInfoContainer: {
    position: 'fixed',
    top: '10px',
    right: '20px',
    zIndex: 1001,
  } as React.CSSProperties,
  userInfoContainerMobile: {
    top: '5px',
    right: '10px',
    left: '70px',
  } as React.CSSProperties,
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    backgroundColor: '#2c3e50',
    padding: '10px 16px',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0, 0, 0, 0.15)',
  } as React.CSSProperties,
  userInfoMobile: {
    padding: '6px 10px',
    gap: '8px',
    fontSize: '0.85rem',
  } as React.CSSProperties,
  userName: {
    fontSize: '0.95rem',
    fontWeight: '500',
    color: '#ecf0f1',
    display: 'block',
  } as React.CSSProperties,
  userNameMobile: {
    fontSize: '0.8rem',
  } as React.CSSProperties,
  tenantId: {
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#e7eaecff',
    marginRight: '6px',
    letterSpacing: '0.3px',
  } as React.CSSProperties,
  tenantIdContainer: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '4px',
  } as React.CSSProperties,
  copyButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '2px 4px',
    color: '#95a5a6',
    transition: 'color 0.2s',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  roleBadge: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  } as React.CSSProperties,
  main: {
    marginTop: '80px',
    marginBottom: '60px',
    minHeight: 'calc(100vh - 140px)',
    padding: '2rem',
  } as React.CSSProperties,
  footer: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60px',
    backgroundColor: '#1a252f',
    color: '#ecf0f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: '2rem',
    paddingRight: '2rem',
    boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
    zIndex: 100,
  } as React.CSSProperties,
  footerMobile: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    height: '50px',
    justifyContent: 'center',
  } as React.CSSProperties,
  footerLinks: {
    display: 'flex',
    gap: '10px',
    marginLeft: 'auto',
    alignItems: 'flex-end',
  } as React.CSSProperties,
  footerLinksMobile: {
    gap: '20px',
    marginLeft: '0',
  } as React.CSSProperties,
  footerLink: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    color: '#ecf0f1',
    textDecoration: 'none',
    fontSize: '0.9rem',
    transition: 'transform 0.2s, opacity 0.2s',
    cursor: 'pointer',
    opacity: 0.8,
  } as React.CSSProperties,
  footerIcon: {
    fontSize: '1.5rem',
  } as React.CSSProperties,
  copyright: {
    fontSize: '0.85rem',
    color: '#95a5a6',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '10px',
  } as React.CSSProperties,
};
