import React from 'react';

export const styles = {
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '80px',
    backgroundColor: '#2c3e50',
    display: 'flex',
    alignItems: 'center',
    padding: '0 2rem',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.1)',
    zIndex: 100,
  } as React.CSSProperties,
  companyName: {
    fontSize: '1.75rem',
    fontWeight: '600',
    color: '#ecf0f1',
    margin: 0,
  } as React.CSSProperties,
  companyNameMobile: {
    fontSize: '1.25rem',
    fontWeight: '600',
    color: '#ecf0f1',
    margin: 0,
  } as React.CSSProperties,
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '1rem',
    paddingTop: '80px',
  } as React.CSSProperties,
  card: {
    backgroundColor: 'white',
    padding: '3rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    textAlign: 'center',
    maxWidth: '400px',
    width: '100%',
  } as React.CSSProperties,
  title: {
    fontSize: '2rem',
    marginBottom: '0.5rem',
    color: '#333',
  } as React.CSSProperties,
  subtitle: {
    fontSize: '1rem',
    color: '#666',
    marginBottom: '2rem',
  } as React.CSSProperties,
  button: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    width: '100%',
    padding: '0.75rem',
    fontSize: '1rem',
    fontWeight: '500',
    color: '#fff',
    backgroundColor: '#4285f4',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    minHeight: '44px',
  } as React.CSSProperties,
  devButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    width: '100%',
    padding: '0.75rem',
    fontSize: '1rem',
    fontWeight: '500',
    color: '#fff',
    backgroundColor: '#28a745',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    marginBottom: '1rem',
    minHeight: '44px',
  } as React.CSSProperties,
  divider: {
    display: 'flex',
    alignItems: 'center',
    margin: '1rem 0',
    color: '#999',
  } as React.CSSProperties,
  dividerText: {
    padding: '0 1rem',
    backgroundColor: 'white',
    position: 'relative',
    zIndex: 1,
  } as React.CSSProperties,
  icon: {
    width: '20px',
    height: '20px',
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '1rem',
    border: '1px solid #ddd',
    borderRadius: '4px',
    marginBottom: '1rem',
    boxSizing: 'border-box',
    minHeight: '44px',
  } as React.CSSProperties,
  error: {
    color: '#dc3545',
    fontSize: '0.875rem',
    marginBottom: '1rem',
    marginTop: '-0.5rem',
  } as React.CSSProperties,
  linkButton: {
    background: 'none',
    border: 'none',
    color: '#4285f4',
    cursor: 'pointer',
    fontSize: '0.875rem',
    textDecoration: 'underline',
    padding: '0.5rem',
    marginTop: '0.5rem',
    minHeight: '44px',
  } as React.CSSProperties,
  googleButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    width: '100%',
    padding: '0.75rem',
    fontSize: '1rem',
    fontWeight: '500',
    color: '#fff',
    backgroundColor: '#4285f4',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    minHeight: '44px',
  } as React.CSSProperties,
};
