import React from 'react';

export const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '2rem',
    marginLeft: '60px',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  containerMobile: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '1rem',
    marginLeft: '0',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  title: {
    fontSize: '2.5rem',
    color: '#333',
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  titleMobile: {
    fontSize: '1.75rem',
    color: '#333',
    marginBottom: '1rem',
  } as React.CSSProperties,
  searchContainer: {
    marginBottom: '1.5rem',
  } as React.CSSProperties,
  searchInput: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '1rem',
    border: '1px solid #ced4da',
    borderRadius: '8px',
    minHeight: '44px',
    boxSizing: 'border-box',
  } as React.CSSProperties,
  categoryContainer: {
    display: 'flex',
    gap: '10px',
    marginBottom: '24px',
    flexWrap: 'wrap',
  } as React.CSSProperties,
  categoryButton: {
    padding: '10px 20px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    background: 'white',
    color: '#333',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 'normal',
    minHeight: '44px',
  } as React.CSSProperties,
  categoryButtonActive: {
    padding: '10px 20px',
    borderRadius: '8px',
    border: '2px solid #4CAF50',
    background: '#4CAF50',
    color: 'white',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 'bold',
    minHeight: '44px',
  } as React.CSSProperties,
  productsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
    gap: '24px',
  } as React.CSSProperties,
  productsGridMobile: {
    display: 'grid',
    gridTemplateColumns: '1fr',
    gap: '16px',
  } as React.CSSProperties,
  card: {
    backgroundColor: 'white',
    padding: '1.5rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
  } as React.CSSProperties,
  cardHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px',
  } as React.CSSProperties,
  cardTitle: {
    margin: '0 0 8px 0',
    fontSize: '20px',
    color: '#333',
  } as React.CSSProperties,
  cardTitleMobile: {
    margin: '0 0 8px 0',
    fontSize: '18px',
    color: '#333',
  } as React.CSSProperties,
  cardSubtitle: {
    margin: '0',
    fontSize: '14px',
    color: '#666',
  } as React.CSSProperties,
  statusBadge: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '12px',
    fontWeight: 'bold',
    color: 'white',
  } as React.CSSProperties,
  description: {
    margin: '0 0 16px 0',
    fontSize: '14px',
    color: '#555',
    lineHeight: '1.5',
  } as React.CSSProperties,
  featuresSection: {
    marginBottom: '16px',
  } as React.CSSProperties,
  featuresTitle: {
    fontSize: '14px',
    color: '#333',
  } as React.CSSProperties,
  feature: {
    marginTop: '8px',
    fontSize: '14px',
    color: '#555',
  } as React.CSSProperties,
  pricingBox: {
    marginBottom: '16px',
    padding: '12px',
    background: '#f5f5f5',
    borderRadius: '8px',
  } as React.CSSProperties,
  pricingLabel: {
    fontSize: '12px',
    color: '#666',
    marginBottom: '4px',
  } as React.CSSProperties,
  pricingValue: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#333',
  } as React.CSSProperties,
  industriesContainer: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '12px',
  } as React.CSSProperties,
  industryTag: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '12px',
    background: '#E3F2FD',
    color: '#1976D2',
  } as React.CSSProperties,
  tagsContainer: {
    display: 'flex',
    gap: '8px',
    flexWrap: 'wrap',
    marginBottom: '16px',
  } as React.CSSProperties,
  tag: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '12px',
    background: '#F5F5F5',
    color: '#666',
  } as React.CSSProperties,
  viewButton: {
    width: '100%',
    padding: '12px',
    borderRadius: '8px',
    border: 'none',
    background: '#2196F3',
    color: 'white',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background 0.2s',
    minHeight: '44px',
  } as React.CSSProperties,
  signupButton: {
    width: '100%',
    padding: '12px',
    borderRadius: '8px',
    border: 'none',
    background: '#4CAF50',
    color: 'white',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background 0.2s',
    minHeight: '44px',
  } as React.CSSProperties,
  loadingCard: {
    backgroundColor: 'white',
    padding: '3rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    maxWidth: '1000px',
    margin: '0 auto',
  } as React.CSSProperties,
  errorText: {
    color: 'red',
  } as React.CSSProperties,
};
