import React from 'react';

export const styles = {
  toggleButton: {
    position: 'fixed',
    left: '80px',
    top: '8px',
    zIndex: 1001,
    padding: '0.5rem 0.75rem',
    fontSize: '1.5rem',
    color: '#ecf0f1',
    backgroundColor: '#2c3e50',
    border: '1px solid #34495e',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'all 0.3s',
    boxShadow: '0 2px 4px rgba(0, 0, 0, 0.2)',
    minHeight: '44px',
    minWidth: '44px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as React.CSSProperties,
  sidebar: {
    position: 'fixed',
    left: 0,
    top: 0,
    bottom: 0,
    width: '250px',
    backgroundColor: '#2c3e50',
    color: '#ecf0f1',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '2px 0 5px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.3s ease-in-out',
    transform: 'translateX(0)',
    zIndex: 1000,
  } as React.CSSProperties,
  sidebarClosed: {
    position: 'fixed',
    left: 0,
    top: 0,
    bottom: 0,
    width: '250px',
    backgroundColor: '#2c3e50',
    color: '#ecf0f1',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '2px 0 5px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.3s ease-in-out',
    transform: 'translateX(-250px)',
    zIndex: 1000,
  } as React.CSSProperties,
  header: {
    padding: '4rem 1.5rem 2rem 1.5rem',
    borderBottom: '1px solid #34495e',
  } as React.CSSProperties,
  title: {
    margin: 0,
    fontSize: '1.5rem',
    fontWeight: '600',
  } as React.CSSProperties,
  nav: {
    flex: 1,
    padding: '1rem 0',
    overflowY: 'auto',
  } as React.CSSProperties,
  navItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.5rem',
    backgroundColor: 'transparent',
    borderTop: 'none',
    borderRight: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    color: '#ecf0f1',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    textAlign: 'left',
    minHeight: '44px',
  } as React.CSSProperties,
  navItemActive: {
    backgroundColor: '#34495e',
    borderLeft: '4px solid #3498db',
  } as React.CSSProperties,
  icon: {
    fontSize: '1.25rem',
    color: '#ffffff',
  } as React.CSSProperties,
  label: {
    fontWeight: '500',
  } as React.CSSProperties,
  footer: {
    padding: '1rem',
    borderTop: '1px solid #34495e',
  } as React.CSSProperties,
  logoutButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.5rem',
    backgroundColor: '#e74c3c',
    border: 'none',
    borderRadius: '4px',
    color: '#fff',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    minHeight: '44px',
  } as React.CSSProperties,
};
