import React from 'react';

export const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '2rem',
    marginLeft: '60px',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  containerMobile: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '1rem',
    marginLeft: '0',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '2rem',
    maxWidth: '800px',
    margin: '0 auto 2rem',
  } as React.CSSProperties,
  title: {
    fontSize: '2rem',
    color: '#333',
  } as React.CSSProperties,
  titleMobile: {
    fontSize: '1.5rem',
    color: '#333',
  } as React.CSSProperties,
  logoutButton: {
    padding: '0.5rem 1.5rem',
    fontSize: '1rem',
    color: '#fff',
    backgroundColor: '#dc3545',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  } as React.CSSProperties,
  card: {
    backgroundColor: 'white',
    padding: '2rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    maxWidth: '800px',
    margin: '0 auto',
  } as React.CSSProperties,
  cardMobile: {
    backgroundColor: 'white',
    padding: '1rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    maxWidth: '800px',
    margin: '0 auto',
  } as React.CSSProperties,
  profileSection: {
    textAlign: 'center',
    paddingBottom: '2rem',
    borderBottom: '1px solid #e0e0e0',
    marginBottom: '2rem',
  } as React.CSSProperties,
  avatar: {
    width: '100px',
    height: '100px',
    borderRadius: '50%',
    marginBottom: '1rem',
    objectFit: 'cover',
    border: '3px solid #e0e0e0',
  } as React.CSSProperties,
  avatarMobile: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    marginBottom: '1rem',
    objectFit: 'cover',
    border: '3px solid #e0e0e0',
  } as React.CSSProperties,
  avatarPlaceholder: {
    width: '100px',
    height: '100px',
    borderRadius: '50%',
    marginBottom: '1rem',
    border: '3px solid #e0e0e0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '3rem',
    backgroundColor: '#f0f0f0',
    margin: '0 auto 1rem',
  } as React.CSSProperties,
  avatarPlaceholderMobile: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    marginBottom: '1rem',
    border: '3px solid #e0e0e0',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '2.5rem',
    backgroundColor: '#f0f0f0',
    margin: '0 auto 1rem',
  } as React.CSSProperties,
  name: {
    fontSize: '1.5rem',
    color: '#333',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  nameMobile: {
    fontSize: '1.25rem',
    color: '#333',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  email: {
    fontSize: '1rem',
    color: '#666',
  } as React.CSSProperties,
  infoSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: '1.25rem',
    color: '#333',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  infoItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0.75rem',
    backgroundColor: '#f8f9fa',
    borderRadius: '4px',
  } as React.CSSProperties,
  label: {
    fontWeight: '500',
    color: '#666',
  } as React.CSSProperties,
  value: {
    color: '#333',
  } as React.CSSProperties,
  navigationSection: {
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '1px solid #e0e0e0',
  } as React.CSSProperties,
  navGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  navGridMobile: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  navButton: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.5rem',
    backgroundColor: '#f8f9fa',
    border: '2px solid transparent',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '1rem',
    minHeight: '44px',
  } as React.CSSProperties,
  navButtonMobile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1rem',
    backgroundColor: '#f8f9fa',
    border: '2px solid transparent',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '0.875rem',
    minHeight: '44px',
  } as React.CSSProperties,
  navIcon: {
    fontSize: '2rem',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  navLabel: {
    fontWeight: '500',
    color: '#333',
  } as React.CSSProperties,
};
