import React from 'react';

export const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#0a0f1a',
    padding: '2rem',
  } as React.CSSProperties,
  containerMobile: {
    minHeight: '100vh',
    backgroundColor: '#0a0f1a',
    padding: '1rem',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: '2rem',
    maxWidth: '800px',
    margin: '0 auto 2rem',
  } as React.CSSProperties,
  title: {
    fontSize: '2rem',
    color: '#ffffff',
    fontWeight: '700',
  } as React.CSSProperties,
  titleMobile: {
    fontSize: '1.5rem',
    color: '#ffffff',
    fontWeight: '700',
  } as React.CSSProperties,
  logoutButton: {
    padding: '0.5rem 1.5rem',
    fontSize: '1rem',
    color: '#fff',
    backgroundColor: '#dc3545',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  } as React.CSSProperties,
  card: {
    backgroundColor: 'rgba(15, 20, 31, 0.9)',
    padding: '2rem',
    borderRadius: '12px',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.5)',
    border: '1px solid rgba(37, 99, 235, 0.2)',
    maxWidth: '800px',
    margin: '0 auto',
  } as React.CSSProperties,
  cardMobile: {
    backgroundColor: 'rgba(15, 20, 31, 0.9)',
    padding: '1rem',
    borderRadius: '12px',
    boxShadow: '0 4px 24px rgba(0, 0, 0, 0.5)',
    border: '1px solid rgba(37, 99, 235, 0.2)',
    maxWidth: '800px',
    margin: '0 auto',
  } as React.CSSProperties,
  profileSection: {
    textAlign: 'center',
    paddingBottom: '2rem',
    borderBottom: '1px solid rgba(37, 99, 235, 0.2)',
    marginBottom: '2rem',
  } as React.CSSProperties,
  avatar: {
    width: '100px',
    height: '100px',
    borderRadius: '50%',
    marginBottom: '1rem',
    objectFit: 'cover',
    border: '3px solid rgba(37, 99, 235, 0.5)',
    boxShadow: '0 0 20px rgba(37, 99, 235, 0.25)',
  } as React.CSSProperties,
  avatarMobile: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    marginBottom: '1rem',
    objectFit: 'cover',
    border: '3px solid rgba(37, 99, 235, 0.5)',
    boxShadow: '0 0 14px rgba(37, 99, 235, 0.25)',
  } as React.CSSProperties,
  avatarPlaceholder: {
    width: '100px',
    height: '100px',
    borderRadius: '50%',
    marginBottom: '1rem',
    border: '2px solid rgba(37, 99, 235, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '3rem',
    background: 'linear-gradient(135deg, rgba(37, 99, 235, 0.15) 0%, rgba(29, 78, 216, 0.08) 100%)',
    margin: '0 auto 1rem',
  } as React.CSSProperties,
  avatarPlaceholderMobile: {
    width: '80px',
    height: '80px',
    borderRadius: '50%',
    marginBottom: '1rem',
    border: '2px solid rgba(37, 99, 235, 0.4)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '2.5rem',
    background: 'linear-gradient(135deg, rgba(37, 99, 235, 0.15) 0%, rgba(29, 78, 216, 0.08) 100%)',
    margin: '0 auto 1rem',
  } as React.CSSProperties,
  name: {
    fontSize: '1.5rem',
    color: '#ffffff',
    marginBottom: '0.5rem',
    fontWeight: '600',
  } as React.CSSProperties,
  nameMobile: {
    fontSize: '1.25rem',
    color: '#ffffff',
    marginBottom: '0.5rem',
    fontWeight: '600',
  } as React.CSSProperties,
  email: {
    fontSize: '1rem',
    color: 'rgba(147, 197, 253, 0.85)',
  } as React.CSSProperties,
  infoSection: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  sectionTitle: {
    fontSize: '1.1rem',
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: '0.75rem',
    fontWeight: '600',
    letterSpacing: '0.3px',
  } as React.CSSProperties,
  infoItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '0.75rem 1rem',
    backgroundColor: 'rgba(37, 99, 235, 0.07)',
    borderRadius: '6px',
    border: '1px solid rgba(37, 99, 235, 0.12)',
  } as React.CSSProperties,
  label: {
    fontWeight: '500',
    color: 'rgba(147, 197, 253, 0.8)',
    fontSize: '0.9rem',
  } as React.CSSProperties,
  value: {
    color: 'rgba(255, 255, 255, 0.9)',
    fontSize: '0.9rem',
  } as React.CSSProperties,
  navigationSection: {
    marginTop: '2rem',
    paddingTop: '2rem',
    borderTop: '1px solid rgba(37, 99, 235, 0.2)',
  } as React.CSSProperties,
  navGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(150px, 1fr))',
    gap: '1rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  navGridMobile: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '0.75rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  navButton: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1.5rem',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    border: '1px solid rgba(37, 99, 235, 0.2)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '1rem',
    minHeight: '44px',
  } as React.CSSProperties,
  navButtonMobile: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '1rem',
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    border: '1px solid rgba(37, 99, 235, 0.2)',
    borderRadius: '10px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    fontSize: '0.875rem',
    minHeight: '44px',
  } as React.CSSProperties,
  navIcon: {
    fontSize: '2rem',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  navLabel: {
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.85)',
  } as React.CSSProperties,
};
