import React from 'react';

export const styles = {
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '100px',
    backgroundColor: '#0a0f1a',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '70px',
    paddingRight: '2rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.5)',
    overflow: 'hidden',
    zIndex: 1000,
  } as React.CSSProperties,
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  } as React.CSSProperties,
  headerContent: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  } as React.CSSProperties,
  companyName: {
    margin: 0,
    fontSize: '2.5rem',
    fontWeight: '700',
    letterSpacing: '-0.5px',
    color: '#ffffff',
    cursor: 'pointer',
    textShadow: '2px 2px 8px rgba(0, 0, 0, 0.7)',
    transition: 'transform 0.2s ease',
  } as React.CSSProperties,
  companyTagline: {
    margin: 0,
    fontSize: '0.9rem',
    fontWeight: '500',
    letterSpacing: '1.5px',
    color: 'rgba(255, 255, 255, 0.85)',
    textTransform: 'uppercase',
    textShadow: '1px 1px 4px rgba(0, 0, 0, 0.7)',
  } as React.CSSProperties,
  companyNameMobile: {
    fontSize: '1.6rem',
    letterSpacing: '0px',
  } as React.CSSProperties,
  userInfoContainer: {
    position: 'fixed',
    top: '22px',
    right: '20px',
    zIndex: 1001,
  } as React.CSSProperties,
  userInfoContainerMobile: {
    top: '5px',
    right: '10px',
    left: '70px',
  } as React.CSSProperties,
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    backgroundColor: 'rgba(15, 20, 31, 0.85)',
    backdropFilter: 'blur(12px)',
    padding: '10px 16px',
    borderRadius: '10px',
    border: '1px solid rgba(37, 99, 235, 0.5)',
    outline: '1px solid rgba(37, 99, 235, 0.18)',
    outlineOffset: '3px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(37,99,235,0.12), inset 0 1px 0 rgba(255,255,255,0.05)',
  } as React.CSSProperties,
  userInfoMobile: {
    padding: '6px 10px',
    gap: '8px',
    fontSize: '0.85rem',
  } as React.CSSProperties,
  userName: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#ffffff',
    display: 'block',
    letterSpacing: '0.2px',
  } as React.CSSProperties,
  userNameMobile: {
    fontSize: '0.8rem',
  } as React.CSSProperties,
  tenantId: {
    fontSize: '0.72rem',
    fontWeight: '500',
    color: 'rgba(147, 197, 253, 0.85)',
    marginRight: '6px',
    letterSpacing: '0.4px',
  } as React.CSSProperties,
  tenantIdContainer: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '4px',
  } as React.CSSProperties,
  copyButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '2px 4px',
    color: '#95a5a6',
    transition: 'color 0.2s',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  roleBadge: {
    padding: '4px 12px',
    borderRadius: '20px',
    fontSize: '0.7rem',
    fontWeight: '700',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  } as React.CSSProperties,
  main: {
    marginTop: '100px',
    marginBottom: '60px',
    minHeight: 'calc(100vh - 160px)',
    padding: '2rem',
  } as React.CSSProperties,
  footer: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    height: '60px',
    backgroundColor: '#0a0f1a',
    color: '#ecf0f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: '2rem',
    paddingRight: '2rem',
    boxShadow: '0 -2px 5px rgba(0, 0, 0, 0.1)',
    zIndex: 100,
  } as React.CSSProperties,
  footerMobile: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    height: '50px',
    justifyContent: 'center',
  } as React.CSSProperties,
  footerLinks: {
    display: 'flex',
    gap: '10px',
    marginLeft: 'auto',
    alignItems: 'flex-end',
  } as React.CSSProperties,
  footerLinksMobile: {
    gap: '20px',
    marginLeft: '0',
  } as React.CSSProperties,
  footerLink: {
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
    color: '#ecf0f1',
    textDecoration: 'none',
    fontSize: '0.9rem',
    transition: 'transform 0.2s, opacity 0.2s',
    cursor: 'pointer',
    opacity: 0.8,
  } as React.CSSProperties,
  footerIcon: {
    fontSize: '1.5rem',
  } as React.CSSProperties,
  copyright: {
    fontSize: '0.85rem',
    color: '#95a5a6',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '10px',
  } as React.CSSProperties,
};
