import React from 'react';

export const styles = {
  header: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '72px',
    backgroundColor: '#0a0f1a',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    paddingLeft: '64px',
    paddingRight: '2rem',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.5)',
    overflow: 'hidden',
    zIndex: 1000,
  } as React.CSSProperties,
  headerBackground: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  } as React.CSSProperties,
  headerContent: {
    position: 'relative',
    zIndex: 2,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  } as React.CSSProperties,
  companyName: {
    margin: 0,
    fontSize: '2rem',
    fontWeight: '700',
    letterSpacing: '-0.5px',
    color: '#ffffff',
    cursor: 'pointer',
    textShadow: '2px 2px 8px rgba(0, 0, 0, 0.7)',
    transition: 'transform 0.2s ease',
  } as React.CSSProperties,
  companyTagline: {
    margin: 0,
    fontSize: '0.9rem',
    fontWeight: '500',
    letterSpacing: '1.5px',
    color: 'rgba(255, 255, 255, 0.85)',
    textTransform: 'uppercase',
    textShadow: '1px 1px 4px rgba(0, 0, 0, 0.7)',
  } as React.CSSProperties,
  companyNameMobile: {
    fontSize: '1.25rem',
    letterSpacing: '0px',
  } as React.CSSProperties,
  userInfoContainer: {
    position: 'fixed',
    top: '8px',
    right: '20px',
    zIndex: 1001,
  } as React.CSSProperties,
  userInfoContainerMobile: {
    top: '5px',
    right: '10px',
    left: '70px',
  } as React.CSSProperties,
  userInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '14px',
    backgroundColor: 'rgba(15, 20, 31, 0.85)',
    backdropFilter: 'blur(12px)',
    padding: '10px 16px',
    borderRadius: '10px',
    border: '1px solid rgba(37, 99, 235, 0.5)',
    outline: '1px solid rgba(37, 99, 235, 0.18)',
    outlineOffset: '3px',
    boxShadow: '0 4px 16px rgba(0, 0, 0, 0.4), 0 0 0 1px rgba(37,99,235,0.12), inset 0 1px 0 rgba(255,255,255,0.05)',
  } as React.CSSProperties,
  userInfoMobile: {
    padding: '6px 10px',
    gap: '8px',
    fontSize: '0.85rem',
  } as React.CSSProperties,
  userName: {
    fontSize: '0.95rem',
    fontWeight: '600',
    color: '#ffffff',
    display: 'block',
    letterSpacing: '0.2px',
  } as React.CSSProperties,
  userNameMobile: {
    fontSize: '0.8rem',
  } as React.CSSProperties,
  tenantId: {
    fontSize: '0.72rem',
    fontWeight: '500',
    color: 'rgba(147, 197, 253, 0.85)',
    marginRight: '6px',
    letterSpacing: '0.4px',
  } as React.CSSProperties,
  tenantIdContainer: {
    display: 'flex',
    alignItems: 'center',
    marginTop: '4px',
  } as React.CSSProperties,
  copyButton: {
    background: 'transparent',
    border: 'none',
    cursor: 'pointer',
    fontSize: '0.9rem',
    padding: '2px 4px',
    color: '#95a5a6',
    transition: 'color 0.2s',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,
  roleBadge: {
    padding: '4px 12px',
    borderRadius: '20px',
    fontSize: '0.7rem',
    fontWeight: '700',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: '0.8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.3)',
  } as React.CSSProperties,
  main: {
    marginTop: '72px',
    marginBottom: '52px',
    minHeight: 'calc(100vh - 124px)',
    padding: '2rem',
    backgroundColor: '#0a0f1a',
  } as React.CSSProperties,
  footer: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    right: 0,
    height: '52px',
    backgroundColor: '#0a0f1a',
    color: '#ecf0f1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: '2rem',
    paddingRight: '2rem',
    boxShadow: '0 -4px 20px rgba(0, 0, 0, 0.35)',
    borderTop: '1px solid rgba(37, 99, 235, 0.15)',
    zIndex: 100,
  } as React.CSSProperties,
  footerMobile: {
    paddingLeft: '1rem',
    paddingRight: '1rem',
    height: '44px',
    justifyContent: 'space-between',
  } as React.CSSProperties,
  footerLinks: {
    display: 'flex',
    gap: '20px',
    alignItems: 'center',
  } as React.CSSProperties,
  footerLinksMobile: {
    gap: '16px',
  } as React.CSSProperties,
  footerLink: {
    color: 'rgba(255, 255, 255, 0.5)',
    textDecoration: 'none',
    fontSize: '0.78rem',
    fontWeight: '500',
    letterSpacing: '0.5px',
    transition: 'color 0.2s',
    cursor: 'pointer',
  } as React.CSSProperties,
  footerIcon: {
    fontSize: '1.5rem',
  } as React.CSSProperties,
  copyright: {
    fontSize: '0.75rem',
    color: 'rgba(255, 255, 255, 0.35)',
    display: 'flex',
    alignItems: 'center',
  } as React.CSSProperties,

  // ── Sidebar toggle button ──────────────────────────────────────────────────
  sidebarToggle: {
    position: 'absolute',
    left: '12px',
    top: '50%',
    transform: 'translateY(-50%)',
    zIndex: 1002,
    padding: '0.3rem 0.5rem',
    fontSize: '1rem',
    lineHeight: 1,
    color: '#e2e8f0',
    backgroundColor: 'rgba(251, 191, 36, 0.15)',
    border: '1px solid rgba(251, 191, 36, 0.5)',
    borderRadius: '5px',
    cursor: 'pointer',
    transition: 'all 0.2s',
    boxShadow: '0 1px 6px rgba(0, 0, 0, 0.4)',
    height: '32px',
    width: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as React.CSSProperties,
  sidebarToggleHover: {
    backgroundColor: 'rgba(251, 191, 36, 0.3)',
    borderColor: 'rgba(251, 191, 36, 0.8)',
    boxShadow: '0 0 8px rgba(251, 191, 36, 0.3)',
  } as React.CSSProperties,

  // ── Sign-in button ─────────────────────────────────────────────────────────
  signInButton: {
    position: 'absolute',
    right: '20px',
    top: '50%',
    transform: 'translateY(-50%)',
    padding: '10px 24px',
    backgroundColor: '#2563eb',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'background-color 0.3s ease',
    minHeight: '44px',
    zIndex: 1000,
  } as React.CSSProperties,
  signInButtonMobile: {
    fontSize: '0.9rem',
  } as React.CSSProperties,

  // ── User info container (row layout) ────────────────────────────────────────
  userInfoRow: {
    right: '20px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    flexDirection: 'row' as const,
  } as React.CSSProperties,

  // ── User avatar ────────────────────────────────────────────────────────────
  userAvatar: {
    width: '36px',
    height: '36px',
    borderRadius: '50%',
    background: 'linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)',
    border: '2px solid rgba(37, 99, 235, 0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '0.95rem',
    fontWeight: '700',
    color: '#ffffff',
    flexShrink: 0,
    boxShadow: '0 0 10px rgba(37, 99, 235, 0.4)',
  } as React.CSSProperties,

  // ── User info vertical divider ─────────────────────────────────────────────
  userInfoDivider: {
    width: '1px',
    height: '32px',
    backgroundColor: 'rgba(37, 99, 235, 0.3)',
    flexShrink: 0,
  } as React.CSSProperties,

  // ── Sidebar dim overlay ────────────────────────────────────────────────────
  sidebarOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    zIndex: 998,
    cursor: 'pointer',
  } as React.CSSProperties,
};
