import { CSSProperties } from 'react';

export const productSignupStyles: { [key: string]: CSSProperties } = {
  container: {
    maxWidth: '900px',
    margin: '0 auto',
  },
  backButton: {
    marginBottom: '24px',
    padding: '8px 16px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    background: 'white',
    color: '#333',
    cursor: 'pointer',
    fontSize: '14px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '24px',
  },
  title: {
    margin: '0 0 12px 0',
    fontSize: '2rem',
    color: '#333',
  },
  category: {
    margin: '0',
    fontSize: '1rem',
    color: '#666',
  },
  statusBadge: {
    padding: '8px 16px',
    borderRadius: '12px',
    fontSize: '14px',
    fontWeight: 'bold',
    color: 'white',
  },
  statusActive: {
    background: '#4CAF50',
  },
  statusInactive: {
    background: '#FFA726',
  },
  section: {
    marginBottom: '32px',
  },
  sectionTitle: {
    fontSize: '1.25rem',
    color: '#333',
    marginBottom: '12px',
  },
  description: {
    fontSize: '1rem',
    color: '#555',
    lineHeight: '1.6',
  },
  featureList: {
    margin: 0,
    paddingLeft: '20px',
  },
  featureItem: {
    fontSize: '1rem',
    color: '#555',
    marginBottom: '8px',
    lineHeight: '1.5',
  },
  pricingBox: {
    marginBottom: '32px',
    padding: '20px',
    background: '#f9f9f9',
    borderRadius: '12px',
    border: '2px solid #e0e0e0',
  },
  pricingText: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
    color: '#2196F3',
    margin: '0',
  },
  pricingDetail: {
    fontSize: '1rem',
    color: '#666',
    fontWeight: 'normal',
  },
  tagContainer: {
    display: 'flex',
    gap: '12px',
    flexWrap: 'wrap',
  },
  industryTag: {
    padding: '8px 16px',
    borderRadius: '20px',
    fontSize: '14px',
    background: '#E3F2FD',
    color: '#1976D2',
    fontWeight: '500',
  },
  tag: {
    padding: '6px 14px',
    borderRadius: '16px',
    fontSize: '13px',
    background: '#F5F5F5',
    color: '#666',
    border: '1px solid #e0e0e0',
  },
  signupSection: {
    borderTop: '2px solid #e0e0e0',
    paddingTop: '32px',
  },
  subscribedContainer: {
    textAlign: 'center' as const,
  },
  subscribedBadge: {
    padding: '20px',
    borderRadius: '12px',
    background: '#E8F5E9',
    border: '2px solid #4CAF50',
    marginBottom: '16px',
  },
  subscribedText: {
    fontSize: '1.25rem',
    color: '#2E7D32',
    fontWeight: 'bold',
    margin: 0,
  },
  browseButton: {
    padding: '14px 32px',
    borderRadius: '8px',
    border: 'none',
    background: '#2196F3',
    color: 'white',
    fontSize: '16px',
    fontWeight: 'bold',
    cursor: 'pointer',
    transition: 'background 0.2s',
  },
  signupContainer: {
    textAlign: 'center' as const,
  },
  signupTitle: {
    fontSize: '1.5rem',
    color: '#333',
    marginBottom: '16px',
  },
  signupDescription: {
    fontSize: '1rem',
    color: '#666',
    marginBottom: '24px',
  },
  signupButton: {
    padding: '16px 48px',
    borderRadius: '8px',
    border: 'none',
    color: 'white',
    fontSize: '18px',
    fontWeight: 'bold',
    transition: 'all 0.2s',
  },
  signupButtonEnabled: {
    background: '#4CAF50',
    cursor: 'pointer',
    boxShadow: '0 4px 12px rgba(76, 175, 80, 0.3)',
  },
  signupButtonDisabled: {
    background: '#ccc',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9999,
  },
  modalContent: {
    background: 'white',
    padding: '32px',
    borderRadius: '12px',
    maxWidth: '800px',
    width: '90%',
    maxHeight: '85vh',
    overflow: 'auto',
    boxShadow: '0 8px 32px rgba(0, 0, 0, 0.2)',
  },
  progressContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '32px',
  },
  progressStep: {
    flex: 1,
    display: 'flex',
    alignItems: 'center',
  },
  progressCircle: {
    width: '40px',
    height: '40px',
    borderRadius: '50%',
    color: 'white',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 'bold',
    fontSize: '18px',
  },
  progressCircleActive: {
    background: '#4CAF50',
  },
  progressCircleInactive: {
    background: '#e0e0e0',
  },
  progressInfo: {
    flex: 1,
    marginLeft: '8px',
  },
  progressLabel: {
    fontSize: '12px',
    color: '#666',
  },
  progressTitle: {
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#333',
  },
  progressLine: {
    flex: 1,
    height: '2px',
    marginLeft: '8px',
  },
  progressLineActive: {
    background: '#4CAF50',
  },
  progressLineInactive: {
    background: '#e0e0e0',
  },
  stepTitle: {
    margin: '0 0 16px 0',
    fontSize: '1.5rem',
    color: '#333',
  },
  termsBox: {
    padding: '16px',
    background: '#f9f9f9',
    borderRadius: '8px',
    marginBottom: '24px',
    maxHeight: '400px',
    overflow: 'auto',
    border: '1px solid #e0e0e0',
  },
  termsSubtitle: {
    fontSize: '1rem',
    margin: '0 0 12px 0',
  },
  termsText: {
    fontSize: '0.9rem',
    lineHeight: '1.6',
    color: '#555',
  },
  termsList: {
    fontSize: '0.9rem',
    lineHeight: '1.8',
    color: '#555',
    paddingLeft: '20px',
  },
  termsFooter: {
    fontSize: '0.85rem',
    color: '#666',
    marginTop: '16px',
    fontStyle: 'italic',
  },
  checkboxContainer: {
    marginBottom: '24px',
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    cursor: 'pointer',
  },
  checkbox: {
    width: '18px',
    height: '18px',
    cursor: 'pointer',
  },
  checkboxText: {
    fontSize: '0.95rem',
    color: '#333',
  },
  buttonContainer: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
  },
  cancelButton: {
    padding: '12px 24px',
    borderRadius: '8px',
    border: '1px solid #ddd',
    background: 'white',
    color: '#333',
    fontSize: '14px',
    fontWeight: 'bold',
    cursor: 'pointer',
  },
  continueButton: {
    padding: '12px 24px',
    borderRadius: '8px',
    border: 'none',
    color: 'white',
    fontSize: '14px',
    fontWeight: 'bold',
  },
  continueButtonEnabled: {
    background: '#4CAF50',
    cursor: 'pointer',
  },
  continueButtonDisabled: {
    background: '#ccc',
    cursor: 'not-allowed',
  },
  stepDescription: {
    fontSize: '0.95rem',
    color: '#666',
    marginBottom: '24px',
  },
  paymentContainer: {
    marginTop: '24px',
  },
  validationSuccessBadge: {
    padding: '20px',
    background: '#E8F5E9',
    border: '2px solid #4CAF50',
    borderRadius: '8px',
    marginBottom: '24px',
  },
  validationSuccessTitle: {
    fontSize: '1rem',
    color: '#2E7D32',
    fontWeight: 'bold',
    margin: '0 0 8px 0',
  },
  validationSuccessText: {
    fontSize: '0.9rem',
    color: '#555',
    margin: 0,
  },
  summaryBox: {
    padding: '20px',
    background: '#f9f9f9',
    borderRadius: '8px',
    marginBottom: '24px',
    border: '1px solid #e0e0e0',
  },
  summaryTitle: {
    fontSize: '1.1rem',
    margin: '0 0 16px 0',
  },
  summaryRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '12px',
  },
  summaryLabel: {
    fontSize: '0.95rem',
    color: '#666',
  },
  summaryValue: {
    fontSize: '0.95rem',
    fontWeight: 'bold',
    color: '#333',
  },
  summaryDivider: {
    borderTop: '1px solid #e0e0e0',
    paddingTop: '12px',
    marginTop: '12px',
  },
  summaryFooter: {
    fontSize: '0.85rem',
    color: '#666',
    margin: 0,
  },
  errorText: {
    color: 'red',
  },
  errorButton: {
    marginTop: '16px',
    padding: '10px 20px',
    borderRadius: '8px',
    border: 'none',
    background: '#2196F3',
    color: 'white',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: 'bold',
  },
  browseButtonHover: {
    background: '#1976D2',
  },
  signupButtonHover: {
    background: '#45a049',
    transform: 'translateY(-2px)',
    boxShadow: '0 6px 16px rgba(76, 175, 80, 0.4)',
  },
  loadingContainer: {
    padding: '40px',
    textAlign: 'center' as const,
  },
  errorContainer: {
    padding: '40px',
    textAlign: 'center' as const,
    color: '#d32f2f',
  },
  errorSubtext: {
    fontSize: '0.9rem',
    color: '#666',
    marginTop: '8px',
  },
  tiersContainer: {
    display: 'flex',
    gap: '20px',
    flexWrap: 'wrap' as const,
    marginTop: '24px',
  },
  tierCard: {
    flex: '1',
    minWidth: '200px',
    padding: '24px',
    border: '2px solid #ddd',
    borderRadius: '12px',
    cursor: 'pointer',
    backgroundColor: '#fff',
    transition: 'all 0.3s ease',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  tierCardSelected: {
    border: '3px solid #4CAF50',
    backgroundColor: '#f1f8f4',
    boxShadow: '0 4px 12px rgba(76, 175, 80, 0.3)',
  },
  tierTitle: {
    margin: '0 0 8px 0',
    color: '#333',
    fontSize: '1.5rem',
  },
  tierPrice: {
    fontSize: '2rem',
    fontWeight: 'bold' as const,
    color: '#4CAF50',
    margin: '12px 0',
  },
  tierPriceUnit: {
    fontSize: '0.9rem',
    color: '#666',
    fontWeight: 'normal' as const,
  },
  tierDescription: {
    color: '#666',
    fontSize: '0.95rem',
    margin: '12px 0',
  },
  tierFeaturesContainer: {
    marginTop: '16px',
    paddingTop: '16px',
    borderTop: '1px solid #eee',
  },
  tierFeaturesTitle: {
    fontWeight: '600' as const,
    margin: '0 0 8px 0',
    fontSize: '0.9rem',
  },
  tierFeaturesList: {
    margin: 0,
    paddingLeft: '20px',
    fontSize: '0.85rem',
    color: '#555',
  },
  tierFeatureItem: {
    marginBottom: '6px',
  },
  tierSelectedBadge: {
    marginTop: '16px',
    padding: '8px',
    backgroundColor: '#4CAF50',
    color: 'white',
    borderRadius: '6px',
    textAlign: 'center' as const,
    fontWeight: '600' as const,
  },
};
