import React from 'react';

export const styles = {
  sidebar: {
    position: 'fixed',
    left: 0,
    top: 0,
    bottom: 0,
    width: '245px',
    backgroundColor: '#0a0f1a',
    background: 'linear-gradient(180deg, #0f1419 0%, #0a0f1a 100%)',
    color: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '4px 0 20px rgba(0, 0, 0, 0.5)',
    borderRight: '1px solid rgba(37, 99, 235, 0.2)',
    transition: 'width 0.3s ease-in-out',
    transform: 'translateX(0)',
    zIndex: 999,
  } as React.CSSProperties,
  sidebarClosed: {
    position: 'fixed',
    left: 0,
    top: 0,
    bottom: 0,
    width: '50px',
    backgroundColor: '#0a0f1a',
    background: 'linear-gradient(180deg, #0f1419 0%, #0a0f1a 100%)',
    color: '#ffffff',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '4px 0 20px rgba(0, 0, 0, 0.5)',
    borderRight: '1px solid rgba(37, 99, 235, 0.2)',
    transition: 'width 0.3s ease-in-out',
    transform: 'translateX(0)',
    zIndex: 997,
  } as React.CSSProperties,
  header: {
    padding: '1.5rem 1.5rem 1.5rem 1.5rem',
    borderBottom: '1px solid rgba(37, 99, 235, 0.2)',
  } as React.CSSProperties,
  title: {
    margin: 0,
    fontSize: '1.5rem',
    fontWeight: '600',
  } as React.CSSProperties,
  nav: {
    flex: 1,
    padding: '0.5rem 0',
    overflowY: 'auto',
    overflowX: 'hidden',
  } as React.CSSProperties,
  navCollapsed: {
    flex: 1,
    padding: '0.5rem 0',
    overflowY: 'auto',
    overflowX: 'hidden',
  } as React.CSSProperties,
  navItem: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.5rem',
    backgroundColor: 'transparent',
    borderTop: 'none',
    borderRight: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    color: '#ffffff',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'left',
    minHeight: '44px',
  } as React.CSSProperties,
  navItemCollapsed: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.8rem 0',
    backgroundColor: 'transparent',
    borderTop: 'none',
    borderRight: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    color: '#ffffff',
    fontSize: '1.1rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    textAlign: 'center',
    minHeight: '40px',
  } as React.CSSProperties,
  navItemActive: {
    backgroundColor: 'rgba(37, 99, 235, 0.35)',
    borderLeft: '4px solid #2563eb',
    boxShadow: 'inset 0 0 12px rgba(37, 99, 235, 0.3)',
    paddingLeft: '1.46rem',
  } as React.CSSProperties,
  navItemActiveCollapsed: {
    backgroundColor: 'rgba(37, 99, 235, 0.4)',
    borderRight: '3px solid #2563eb',
    boxShadow: 'inset -3px 0 12px rgba(37, 99, 235, 0.3)',
  } as React.CSSProperties,
  icon: {
    fontSize: '1.2rem',
    color: '#ffffff',
  } as React.CSSProperties,
  iconWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '20px',
    height: '20px',
    flexShrink: 0,
    color: '#ffffff',
  } as React.CSSProperties,
  label: {
    fontWeight: '500',
  } as React.CSSProperties,
  footer: {
    padding: '1rem',
    borderTop: '1px solid rgba(37, 99, 235, 0.2)',
  } as React.CSSProperties,
  logoutButton: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    padding: '1rem 1.5rem',
    backgroundColor: 'transparent',
    border: '1px solid rgba(37, 99, 235, 0.3)',
    borderRadius: '6px',
    color: '#ffffff',
    fontSize: '1rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    minHeight: '44px',
  } as React.CSSProperties,
  logoutButtonCollapsed: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '0.8rem 0',
    backgroundColor: 'transparent',
    border: '1px solid rgba(37, 99, 235, 0.3)',
    borderRadius: '6px',
    color: '#ffffff',
    fontSize: '1.1rem',
    cursor: 'pointer',
    transition: 'all 0.2s',
    minHeight: '40px',
  } as React.CSSProperties,
};
