import React from 'react';

export const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '2rem',
    marginLeft: '60px',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  card: {
    backgroundColor: 'white',
    padding: '3rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    maxWidth: '1200px',
    margin: '0 auto',
  } as React.CSSProperties,
  title: {
    fontSize: '2.5rem',
    color: '#333',
    marginBottom: '1rem',
  } as React.CSSProperties,
  description: {
    fontSize: '1.125rem',
    color: '#666',
    lineHeight: '1.6',
    marginBottom: '2rem',
  } as React.CSSProperties,
  error: {
    color: '#dc3545',
    fontSize: '1rem',
    marginTop: '1rem',
    padding: '12px',
    backgroundColor: '#f8d7da',
    borderRadius: '4px',
  } as React.CSSProperties,
  tenantsContainer: {
    marginTop: '2rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
  } as React.CSSProperties,
  tenantCard: {
    border: '1px solid #dee2e6',
    borderRadius: '8px',
    overflow: 'hidden',
    backgroundColor: '#fff',
  } as React.CSSProperties,
  tenantHeader: {
    padding: '1.5rem',
    backgroundColor: '#f8f9fa',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    transition: 'background-color 0.2s',
  } as React.CSSProperties,
  tenantInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  } as React.CSSProperties,
  tenantId: {
    margin: 0,
    fontSize: '1.25rem',
    color: '#333',
    fontFamily: 'monospace',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
  } as React.CSSProperties,
  tenantIcon: {
    fontSize: '1.5rem',
  } as React.CSSProperties,
  userCount: {
    backgroundColor: '#007bff',
    color: 'white',
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '0.875rem',
    fontWeight: '600',
  } as React.CSSProperties,
  expandIcon: {
    fontSize: '1rem',
    color: '#666',
  } as React.CSSProperties,
  usersSection: {
    padding: '1rem',
    borderTop: '1px solid #dee2e6',
  } as React.CSSProperties,
  userTable: {
    width: '100%',
    borderCollapse: 'collapse',
  } as React.CSSProperties,
  tableHeader: {
    backgroundColor: '#f8f9fa',
  } as React.CSSProperties,
  th: {
    padding: '12px',
    textAlign: 'left',
    fontWeight: '600',
    color: '#333',
    borderBottom: '2px solid #dee2e6',
  } as React.CSSProperties,
  tableRow: {
    borderBottom: '1px solid #dee2e6',
  } as React.CSSProperties,
  td: {
    padding: '12px',
    color: '#666',
  } as React.CSSProperties,
  roleBadge: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    display: 'inline-block',
  } as React.CSSProperties,
  noUsers: {
    textAlign: 'center',
    color: '#999',
    padding: '1rem',
    fontStyle: 'italic',
  } as React.CSSProperties,
  noData: {
    textAlign: 'center',
    color: '#999',
    padding: '2rem',
    fontSize: '1rem',
  } as React.CSSProperties,
  infoBox: {
    marginTop: '3rem',
    padding: '1.5rem',
    backgroundColor: '#e7f3ff',
    borderRadius: '8px',
    borderLeft: '4px solid #007bff',
  } as React.CSSProperties,
  infoTitle: {
    margin: '0 0 1rem 0',
    fontSize: '1.25rem',
    color: '#333',
  } as React.CSSProperties,
  infoList: {
    margin: 0,
    paddingLeft: '1.5rem',
    color: '#666',
    lineHeight: '1.8',
  } as React.CSSProperties,
};
