import React from 'react';

export const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '2rem',
    marginLeft: '60px',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  containerMobile: {
    minHeight: '100vh',
    backgroundColor: '#f5f5f5',
    padding: '1rem',
    marginLeft: '0',
    transition: 'margin-left 0.3s',
  } as React.CSSProperties,
  card: {
    backgroundColor: 'white',
    padding: '3rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    maxWidth: '1000px',
    margin: '0 auto',
  } as React.CSSProperties,
  cardMobile: {
    backgroundColor: 'white',
    padding: '1.5rem',
    borderRadius: '8px',
    boxShadow: '0 2px 10px rgba(0, 0, 0, 0.1)',
    maxWidth: '1000px',
    margin: '0 auto',
  } as React.CSSProperties,
  title: {
    fontSize: '2.5rem',
    color: '#333',
    marginBottom: '1rem',
  } as React.CSSProperties,
  titleMobile: {
    fontSize: '1.75rem',
    color: '#333',
    marginBottom: '0.75rem',
  } as React.CSSProperties,
  description: {
    fontSize: '1.125rem',
    color: '#666',
    lineHeight: '1.6',
  } as React.CSSProperties,
  descriptionMobile: {
    fontSize: '1rem',
    color: '#666',
    lineHeight: '1.5',
  } as React.CSSProperties,
  error: {
    color: '#dc3545',
    fontSize: '1rem',
    marginTop: '1rem',
  } as React.CSSProperties,
  tableContainer: {
    marginTop: '2rem',
    overflowX: 'auto',
  } as React.CSSProperties,
  table: {
    width: '100%',
    borderCollapse: 'collapse',
  } as React.CSSProperties,
  tableHeader: {
    backgroundColor: '#f8f9fa',
  } as React.CSSProperties,
  th: {
    padding: '12px',
    textAlign: 'left',
    fontWeight: '600',
    color: '#333',
    borderBottom: '2px solid #dee2e6',
  } as React.CSSProperties,
  tableRow: {
    borderBottom: '1px solid #dee2e6',
  } as React.CSSProperties,
  td: {
    padding: '12px',
    color: '#666',
  } as React.CSSProperties,
  roleBadge: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '0.75rem',
    fontWeight: '600',
    color: '#fff',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    display: 'inline-block',
  } as React.CSSProperties,
  tenantCode: {
    backgroundColor: '#f8f9fa',
    padding: '4px 8px',
    borderRadius: '4px',
    fontSize: '0.875rem',
    fontFamily: 'monospace',
  } as React.CSSProperties,
  actionButtons: {
    display: 'flex',
    gap: '8px',
  } as React.CSSProperties,
  editButton: {
    padding: '6px 12px',
    backgroundColor: '#007bff',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.875rem',
  } as React.CSSProperties,
  saveButton: {
    padding: '6px 12px',
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.875rem',
  } as React.CSSProperties,
  cancelButton: {
    padding: '6px 12px',
    backgroundColor: '#6c757d',
    color: 'white',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '0.875rem',
  } as React.CSSProperties,
  select: {
    padding: '6px',
    borderRadius: '4px',
    border: '1px solid #ced4da',
    fontSize: '0.875rem',
    minWidth: '200px',
  } as React.CSSProperties,
  noData: {
    textAlign: 'center',
    color: '#999',
    padding: '2rem',
    fontSize: '1rem',
  } as React.CSSProperties,
  headerContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '1rem',
    gap: '2rem',
  } as React.CSSProperties,
  createButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '12px 24px',
    backgroundColor: '#28a745',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '1rem',
    fontWeight: '600',
    whiteSpace: 'nowrap',
    minHeight: '44px',
    transition: 'background-color 0.2s',
  } as React.CSSProperties,
  buttonIcon: {
    fontSize: '1.2rem',
  } as React.CSSProperties,
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  } as React.CSSProperties,
  modal: {
    backgroundColor: 'white',
    borderRadius: '8px',
    padding: '2rem',
    maxWidth: '500px',
    width: '90%',
    maxHeight: '90vh',
    overflowY: 'auto',
    boxShadow: '0 4px 20px rgba(0, 0, 0, 0.15)',
  } as React.CSSProperties,
  modalTitle: {
    fontSize: '1.5rem',
    fontWeight: '600',
    color: '#333',
    marginBottom: '1.5rem',
    marginTop: 0,
  } as React.CSSProperties,
  formGroup: {
    marginBottom: '1.25rem',
  } as React.CSSProperties,
  label: {
    display: 'block',
    fontSize: '0.875rem',
    fontWeight: '600',
    color: '#333',
    marginBottom: '0.5rem',
  } as React.CSSProperties,
  input: {
    width: '100%',
    padding: '0.75rem',
    fontSize: '1rem',
    border: '1px solid #ced4da',
    borderRadius: '4px',
    boxSizing: 'border-box',
    minHeight: '44px',
  } as React.CSSProperties,
  modalActions: {
    display: 'flex',
    gap: '1rem',
    marginTop: '2rem',
    justifyContent: 'flex-end',
  } as React.CSSProperties,
  searchFilterContainer: {
    display: 'flex',
    gap: '1rem',
    marginTop: '2rem',
    marginBottom: '1rem',
    alignItems: 'center',
    flexWrap: 'wrap',
  } as React.CSSProperties,
  searchInput: {
    flex: 1,
    minWidth: '250px',
    padding: '0.75rem',
    fontSize: '1rem',
    border: '1px solid #ced4da',
    borderRadius: '4px',
    minHeight: '44px',
  } as React.CSSProperties,
  filterSelect: {
    padding: '0.75rem',
    fontSize: '1rem',
    border: '1px solid #ced4da',
    borderRadius: '4px',
    minHeight: '44px',
    minWidth: '150px',
    backgroundColor: 'white',
  } as React.CSSProperties,
};
